using UnityEngine;

namespace RyanAssets.Characters.Client {
    /// <summary>
    /// Receives collision callbacks on the character Rigidbody and removes upward velocity
    /// generated by running into near-vertical surfaces. CharacterMovement lives on the client
    /// object, so it cannot receive these callbacks directly.
    /// </summary>
    public sealed class CharacterCollisionRelay : MonoBehaviour {
        private const float MaximumWallNormalY = 0.35f;
        private const float MinimumIntoWallSpeed = 0.01f;

        private Rigidbody _rigidbody;
        private CharacterMovement _movement;

        public void Initialize(Rigidbody body, CharacterMovement movement) {
            _rigidbody = body;
            _movement = movement;
        }

        private void OnCollisionEnter(Collision collision) {
            StabilizeWallCollision(collision);
        }

        private void OnCollisionStay(Collision collision) {
            StabilizeWallCollision(collision);
        }

        private void StabilizeWallCollision(Collision collision) {
            if (_rigidbody == null || _movement == null || _rigidbody.linearVelocity.y <= 0f || _movement.IsJumpVelocityProtected)
                return;

            // The solver may already have removed the into-wall portion from the Rigidbody by
            // the time this callback runs. Collision.relativeVelocity retains the impact that
            // produced the contact, which lets us distinguish a wall hit from merely resting
            // beside a wall.
            Vector3 planarImpactVelocity = Vector3.ProjectOnPlane(collision.relativeVelocity, Vector3.up);
            for (int i = 0; i < collision.contactCount; i++) {
                Vector3 normal = collision.GetContact(i).normal;
                if (normal.y > MaximumWallNormalY)
                    continue;

                Vector3 planarNormal = Vector3.ProjectOnPlane(normal, Vector3.up);
                if (planarNormal.sqrMagnitude < 0.001f || planarImpactVelocity.sqrMagnitude < MinimumIntoWallSpeed * MinimumIntoWallSpeed)
                    continue;

                Vector3 velocity = _rigidbody.linearVelocity;
                velocity.y = 0f;
                _rigidbody.linearVelocity = velocity;
                return;
            }
        }
    }
}
