using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RpcGen {
    [Generator]
    public class SharedRpcIncrementalGenerator : IIncrementalGenerator {
        public void Initialize(IncrementalGeneratorInitializationContext context) {
            context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
                "RpcAttribute.g.cs",
                """
                using System;
                namespace RpcGen
                {
                    [AttributeUsage(AttributeTargets.Method)]
                    public class SharedRpcAttribute : Attribute
                    {
                        public bool RunOnServer { get; set; } = true;
                    }
                }
                """));

            var methods = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "RpcGen.SharedRpcAttribute",
                    predicate: static (node, _) => node is MethodDeclarationSyntax,
                    transform: static (ctx, _) => ctx)
                .Where(static ctx => ctx.TargetSymbol is IMethodSymbol);

            context.RegisterSourceOutput(methods, Generate);
        }

        private static void Generate(SourceProductionContext context, GeneratorAttributeSyntaxContext ctx) {
            var method = (IMethodSymbol)ctx.TargetSymbol;
            var containingType = method.ContainingType;

            bool runOnServer = true;
            foreach (var namedArg in ctx.Attributes[0].NamedArguments) {
                if (namedArg.Key == "RunOnServer" && namedArg.Value.Value is bool b)
                    runOnServer = b;
            }

            var className = containingType.Name;
            var ns = containingType.ContainingNamespace.IsGlobalNamespace
                ? null
                : containingType.ContainingNamespace.ToDisplayString();

            var methodName = method.Name;
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
            var args = string.Join(", ", method.Parameters.Select(p => p.Name));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            if (ns is not null) sb.AppendLine($"namespace {ns} {{");

            sb.AppendLine($"public partial class {className}");
            sb.AppendLine("{");

            sb.AppendLine("    [ObserverRpc]");
            sb.AppendLine($"    void {methodName}ObserverRpc({parameters})");
            sb.AppendLine("    {");
            sb.AppendLine($"        {methodName}({args});");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    [ServerRpc]");
            sb.AppendLine($"    void {methodName}ServerRpc({parameters})");
            sb.AppendLine("    {");
            if (runOnServer)
                sb.AppendLine($"        {methodName}({args});");
            else
                sb.AppendLine($"        // RunOnServer = false: not invoked locally on the server");
            sb.AppendLine($"        {methodName}ObserverRpc({args});");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    void {methodName}Client({parameters})");
            sb.AppendLine("    {");
            sb.AppendLine($"        {methodName}({args});");
            sb.AppendLine($"        {methodName}ServerRpc({args});");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            if (ns is not null) sb.AppendLine("}");

            context.AddSource($"{className}_{methodName}_Rpc.g.cs", sb.ToString());
        }
    }
}