// using System;
// using System.Linq;
// using System.Text;
// using Microsoft.CodeAnalysis;
// using Microsoft.CodeAnalysis.CSharp;
// using Microsoft.CodeAnalysis.CSharp.Syntax;

// namespace RpcGen {
//     // This uses the classic source-generator API because Unity/FishNet ships
//     // Roslyn 3.x. IIncrementalGenerator requires a newer Roslyn runtime.
//     [Generator]
//     public sealed class SharedRpcGenerator : ISourceGenerator {
//         public void Initialize(GeneratorInitializationContext context) {
//             context.RegisterForSyntaxNotifications(() => new CandidateReceiver());
//         }

//         public void Execute(GeneratorExecutionContext context) {
//             var receiver = context.SyntaxReceiver as CandidateReceiver;
//             if (receiver == null)
//                 return;

//             foreach (var declaration in receiver.Methods) {
//                 var model = context.Compilation.GetSemanticModel(declaration.SyntaxTree);
//                 var method = model.GetDeclaredSymbol(declaration) as IMethodSymbol;
//                 if (method == null)
//                     continue;

//                 var attribute = method.GetAttributes().FirstOrDefault(a =>
//                     a.AttributeClass != null &&
//                     a.AttributeClass.ToDisplayString() == "RpcGen.SharedRpcAttribute");
//                 if (attribute == null)
//                     continue;

//                 Generate(context, method, attribute);
//             }
//         }

//         private static void Generate(
//             GeneratorExecutionContext context,
//             IMethodSymbol method,
//             AttributeData attribute) {
//             var containingType = method.ContainingType;
//             var declaration = containingType.DeclaringSyntaxReferences
//                 .Select(r => r.GetSyntax())
//                 .OfType<ClassDeclarationSyntax>()
//                 .FirstOrDefault();

//             if (declaration == null || !containingType.DeclaringSyntaxReferences
//                     .Select(r => r.GetSyntax())
//                     .OfType<ClassDeclarationSyntax>()
//                     .All(c => c.Modifiers.Any(SyntaxKind.PartialKeyword))) {
//                 context.ReportDiagnostic(Diagnostic.Create(
//                     new DiagnosticDescriptor(
//                         "RPCGEN001",
//                         "SharedRpc requires a partial class",
//                         "The class containing '{0}' must be declared partial so SharedRpc can generate its FishNet RPC methods",
//                         "RpcGen",
//                         DiagnosticSeverity.Error,
//                         true),
//                     method.Locations.FirstOrDefault(), method.Name));
//                 return;
//             }

//             var runOnServer = true;
//             var runOnCallingClient = true;
//             foreach (var namedArgument in attribute.NamedArguments) {
//                 if (namedArgument.Key == "RunOnServer" && namedArgument.Value.Value is bool server)
//                     runOnServer = server;
//                 else if (namedArgument.Key == "RunOnCallingClient" && namedArgument.Value.Value is bool client)
//                     runOnCallingClient = client;
//             }

//             var ns = containingType.ContainingNamespace.IsGlobalNamespace
//                 ? null
//                 : containingType.ContainingNamespace.ToDisplayString();
//             var parameters = string.Join(", ", method.Parameters.Select(p =>
//                 p.Type.ToDisplayString() + " " + p.Name));
//             var arguments = string.Join(", ", method.Parameters.Select(p => p.Name));
//             var className = containingType.Name;
//             var methodName = method.Name;

//             var source = new StringBuilder();
//             source.AppendLine("// <auto-generated/>");
//             if (ns != null)
//                 source.AppendLine("namespace " + ns + " {");
//             source.AppendLine("public partial class " + className);
//             source.AppendLine("{");
//             source.AppendLine("    [global::FishNet.Object.ObserversRpc(ExcludeOwner = true)]");
//             source.AppendLine("    void " + methodName + "ObserverRpc(" + parameters + ")");
//             source.AppendLine("    {");
//             source.AppendLine("        " + methodName + "(" + arguments + ");");
//             source.AppendLine("    }");
//             source.AppendLine();
//             source.AppendLine("    [global::FishNet.Object.ServerRpc]");
//             source.AppendLine("    void " + methodName + "ServerRpc(" + parameters + ")");
//             source.AppendLine("    {");
//             if (runOnServer)
//                 source.AppendLine("        " + methodName + "(" + arguments + ");");
//             source.AppendLine("        " + methodName + "ObserverRpc(" + arguments + ");");
//             source.AppendLine("    }");
//             source.AppendLine();
//             source.AppendLine("    public void " + methodName + "Client(" + parameters + ")");
//             source.AppendLine("    {");
//             if (runOnCallingClient)
//                 source.AppendLine("        " + methodName + "(" + arguments + ");");
//             source.AppendLine("        " + methodName + "ServerRpc(" + arguments + ");");
//             source.AppendLine("    }");
//             source.AppendLine("}");
//             if (ns != null)
//                 source.AppendLine("}");

//             context.AddSource(className + "_" + methodName + "_Rpc.g.cs", source.ToString());
//         }

//         private sealed class CandidateReceiver : ISyntaxReceiver {
//             public readonly System.Collections.Generic.List<MethodDeclarationSyntax> Methods =
//                 new System.Collections.Generic.List<MethodDeclarationSyntax>();

//             public void OnVisitSyntaxNode(SyntaxNode node) {
//                 var method = node as MethodDeclarationSyntax;
//                 if (method != null && method.AttributeLists.Count != 0)
//                     Methods.Add(method);
//             }
//         }
//     }
// }
